# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
# geo-api
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
      - id: isort
        files: ^geo-api
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        files: ^geo-api/
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: ["--config=geo-api/app/.flake8", "--ignore=E203,W503"]
        files: ^geo-api/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.770'
    hooks:
    -   id: mypy
        args: ["--config-file", "geo-api/app/mypy.ini"]
        additional_dependencies:
            - 'pydantic==1.6.1'
            - 'sqlalchemy-stubs'
        files: ^geo-api/
# editor
-   repo: local
    hooks:
    -   id: gia-editor
        name: git-editor run eslint and prettier
        language: system
        entry: bash -c 'cd gia-editor && exec npx eslint src --fix --ext .js,.vue && exec npx prettier --write --list-different --ignore-unknown src'
        pass_filenames: false
        types: [text]
        files: ^gia-editor/src/.*\.(vue|js)$
