version: '3.1'

services:
  postgis:
    image: postgis/postgis:latest
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gia
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=master
    ports:
      - 5432:5432