version: '3.1'

services:
  postgis:
    image: postgis/postgis:latest
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=master
    ports:
      - 5432:5432
  webserver:
    build: .
    volumes:
    - ./:/app
    ports:
    - 80:80
    environment:
      - DATABASE_URL=postgresql://master:master@postgis:5432/development
      - JWT_SECRET=mRJZQrLE6HlStXd4eEQcMLNDDIltgo1eYUzA5TbAcaRlwCX6FI2SLYKjgq19
      - MAPBOX_TOKEN=pk.eyJ1IjoidGVmcHgiLCJhIjoiY2s3dTg3N2YzMDB2MjNvbW92b3g2dGpybyJ9.PVGtG461oWUisZPnfZx-uw