service: geo-api
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  region: eu-north-1
  profile: ${opt:profile, self:custom.stageVars.profile}
  memorySize: 3008
  timeout: 30
  environment:
    MAPBOX_TOKEN: ${self:custom.stageVars.environment.MAPBOX_TOKEN}
    DATABASE_URL: ${self:custom.stageVars.environment.DATABASE_URL}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  defaultStage: dev
  stageVars: ${file(serverless/config/${self:provider.stage}.yml)}
  pythonRequirements:
    dockerizePip: true
  apigwBinary:
    types:
      - 'image/png'
      - '*/*'

package:
  exclude:
    - venv/**
    - node_modules/**
functions:
  - ${file(serverless/functions/collections.yml)}
  - ${file(serverless/functions/items.yml)}
  - ${file(serverless/functions/misc.yml)}

