service: api-collection
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-north-1
  memorySize: 3008
  timeout: 30 # op
  environment:
    DATABASE_URI: ${env:DATABASE_URI}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  pythonRequirements:
    dockerizePip: true
package:
  exclude:
    - venv/**
    - node_modules/**
functions:
  - ${file(serverless/functions/collections.yml)}
  - ${file(serverless/functions/items.yml)}
  - ${file(serverless/functions/misc.yml)}

