service: geo-api
provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  region: eu-north-1
  profile: ${opt:profile, self:custom.stageVars.profile}
  memorySize: 3008
  timeout: 30
  environment:
    MAPBOX_TOKEN: ${self:custom.stageVars.environment.MAPBOX_TOKEN}
    DATABASE_URL: ${self:custom.stageVars.environment.DATABASE_URL}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-aws-documentation
  - serverless-finch
custom:
  defaultStage: dev
  stageVars: ${file(serverless/config/${self:provider.stage}.yml)}
  pythonRequirements:
    dockerizePip: true
  apigwBinary:
    types:
      - 'image/png'
      - '*/*'
  documentation:
    api: ${file(serverless/documentation/api.yml)}
    models: ${file(serverless/documentation/models.yml)}

  client:
    bucketName: ${self:service}-${self:provider.stage}-static
    distributionFolder: static
package:
  exclude:
    - venv/**
    - node_modules/**
    - static/**
functions:
  - ${file(serverless/functions/collections.yml)}
  #- ${file(serverless/functions/items.yml)}
  - ${file(serverless/functions/misc.yml)}

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'