service: api-collection
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-north-1
  memorySize: 3008
  timeout: 30 # op
  environment:
    MAPBOX_TOKEN: ${env:MAPBOX_TOKEN}
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  pythonRequirements:
    dockerizePip: true
  apigwBinary:
    types:
      - 'image/png'
      - '*/*'

package:
  exclude:
    - venv/**
    - node_modules/**
functions:
  - ${file(serverless/functions/collections.yml)}
  - ${file(serverless/functions/items.yml)}
  - ${file(serverless/functions/misc.yml)}

