service: api-collection
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-north-1

  environment:
    DATABASE_URI: ${env:DATABASE_URI}

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  pythonRequirements:
    dockerizePip: true
package:
  exclude:
    - venv/**
    - node_modules/**
functions:
  ping:
    handler: app.handlers.handler.ping
    events:
      - http:
          path: ping
          method: get
  collections-index:
    handler: app.handlers.geo_collections.index
    events:
      - http:
          path: collections
          method: get