name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-18.04
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: Future-Position-X/generate-plantuml-action@master
      with:
        path: diagrams
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}